### PR TITLE
Add minimum perl using dzil plugin [MinimumPerlFast]

### PR DESCRIPTION
**Pull request by manwar**
Hi @xsawyerx 

Sorry for other PR https://github.com/xsawyerx/app-unansi/pull/1 
Please review this one as it is using better suited plugin [MinimumPerlFast].

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by xsawyerx** [comment]
@manwar Have you tried it before submitting it?

**Comment by manwar** [comment]
Yes, I have this time.

**Comment by manwar** [comment]
I suggest adding travis to catch any error in PR

**Comment by xsawyerx** [comment]
Patches welcome for that too. :)

Thank you for this contribution!

**Pull request merged**
